//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuckyDraw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prize
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public bool State { get; set; }
        public decimal Percent { get; set; }
        public int Count { get; set; }
        public string Detail { get; set; }
        public Nullable<decimal> Angle { get; set; }
        public Nullable<int> Order { get; set; }
    }
}
